# Generated by Django 6.0.5 on 2026-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(
                blank=True, related_name='members', to='service_requests.department'),
        ),
    ]
