# Generated by Django 6.0.5 on 2026-05-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_department_user_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('department_staff', 'Department Staff'), ('departmental_director', 'Departmental Director'), ('communication_director', 'Communication Director'), ('media_team', 'Media Team'), ('admin', 'Admin')], default='department_staff', max_length=30),
        ),
    ]
