# Generated by Django 6.0.5 on 2026-05-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this service type is available for new requests'),
        ),
    ]
