# Generated by Django 6.0.5 on 2026-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('request_assigned', 'Request Assigned'), ('request_rejected', 'Request Rejected'), ('progress_updated', 'Progress Updated'), ('comment_added', 'Comment Added'), ('request_completed', 'Request Completed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
